title: "WEM"
description: "WEM은 인터렉티브 시네마와 기능성 게임을 제작하는 성균관대학교 글로벌융합학부 학회입니다."
url: "https://wem-skku.github.io"
baseurl: "/WEM_DemoSite"
lang: "ko-KR"
timezone: "Asia/Seoul"
markdown: kramdown
permalink: pretty

collections:
  works:
    output: true
    permalink: /works/:name/
  records:
    output: true
    permalink: /records/:name/

defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "records"
    values:
      layout: "record"

exclude:
  - README-assets
  - node_modules
  - vendor
